Updates to scripts

diff --git a/chezmoi/.chezmoiscripts/run_before_01-install-homebrew-op.sh.tmpl b/chezmoi/.chezmoiscripts/run_before_01-install-homebrew-op.sh.tmpl
--- a/chezmoi/.chezmoiscripts/run_before_01-install-homebrew-op.sh.tmpl
+++ b/chezmoi/.chezmoiscripts/run_before_01-install-homebrew-op.sh.tmpl
@@ -1,5 +1,12 @@
-#!{{ lookPath "bash" }}
-set -euo pipefail
+#!/usr/bin/env bash
+
+set -o errexit                # Exit on error. Append || true if you expect an error.
+set -o errtrace               # Exit on error inside any functions or subshells.
+set -o noclobber              # Don't allow overwriting files.
+set -o nounset                # Don't allow use of undefined vars. Use ${VAR:-} to use an undefined VAR.
+set -o pipefail               # Produce a failure return code if any pipeline command errors.
+shopt -s failglob             # Cause globs that don't get expanded to cause errors.
+shopt -s globstar 2>/dev/null # Match all files and zero or more sub-directories.
 
 # For homebrew
 # Adds $HOMEBREW_PREFIX/bin as prefix to PATH.
@@ -68,6 +75,8 @@ fi
 if ! op whoami >/dev/null 2>&1; then
     echo
     echo "Logging into 1Password..."
+
+    # OP_SESSION_IPSQ5XJ7FFEKLI5OALM3AREXS4="P-qJ5s9_QYZmGScSWATJh878T2XE1W7ZIJOdifjsZ9Q"
 
     eval "$(op signin --account {{ .opaccount }} )"
 fi
