Fix scripts

diff --git a/chezmoi/.chezmoiscripts/run_after_99-chezmoi-unmanaged.sh.tmpl b/chezmoi/.chezmoiscripts/run_after_99-chezmoi-unmanaged.sh.tmpl
--- a/chezmoi/.chezmoiscripts/run_after_99-chezmoi-unmanaged.sh.tmpl
+++ b/chezmoi/.chezmoiscripts/run_after_99-chezmoi-unmanaged.sh.tmpl
@@ -1,4 +1,4 @@
-{{  if eq .chezmoi.os "windows" }}
+{{ if eq .chezmoi.os "windows" -}}
 # Set strict error handling
 $ErrorActionPreference = "Stop"  # Exit on error
 Set-StrictMode -Version Latest   # Disallow undefined variables
@@ -19,10 +19,15 @@ function SafeWrite-File {
 Write-Host ""
 Write-Host "Files unmanaged by chezmoi:"
 chezmoi unmanaged
-{{ else }}
+{{ else -}}
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -o errexit    # Exit on error. Append || true if you expect an error.
+set -o errtrace   # Exit on error inside any functions or subshells.
+set -o noclobber  # don't allow overwriting files
+set -o nounset    # Don't allow use of undefined vars. Use ${VAR:-} to use an undefined VAR.
+set -o pipefail   # Produce a failure return code if any pipeline command errors
+shopt -s failglob # Cause globs that don't get expanded to cause errors
 
 echo
 echo "Files unmanaged by chezmoi:"
diff --git a/chezmoi/.chezmoiscripts/run_onchange_41-symlink-zsh-aliases.sh.tmpl b/chezmoi/.chezmoiscripts/run_onchange_41-symlink-zsh-aliases.sh.tmpl
--- a/chezmoi/.chezmoiscripts/run_onchange_41-symlink-zsh-aliases.sh.tmpl
+++ b/chezmoi/.chezmoiscripts/run_onchange_41-symlink-zsh-aliases.sh.tmpl
@@ -1,7 +1,12 @@
-{{  if ne .chezmoi.os "windows" }}
+{{ if ne .chezmoi.os "windows" -}}
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -o errexit    # Exit on error. Append || true if you expect an error.
+set -o errtrace   # Exit on error inside any functions or subshells.
+set -o noclobber  # don't allow overwriting files
+set -o nounset    # Don't allow use of undefined vars. Use ${VAR:-} to use an undefined VAR.
+set -o pipefail   # Produce a failure return code if any pipeline command errors
+shopt -s failglob # Cause globs that don't get expanded to cause errors
 
 echo
 echo
diff --git a/chezmoi/.chezmoiscripts/run_onchange_after_83-install-mise-packages.sh.tmpl b/chezmoi/.chezmoiscripts/run_onchange_after_83-install-mise-packages.sh.tmpl
--- a/chezmoi/.chezmoiscripts/run_onchange_after_83-install-mise-packages.sh.tmpl
+++ b/chezmoi/.chezmoiscripts/run_onchange_after_83-install-mise-packages.sh.tmpl
@@ -1,16 +1,26 @@
-# mise config hash: {{ include "./private_dot_config/mise/config.toml.tmpl " | sha256sum }}
-{{  if eq .chezmoi.os "windows" }}
+{{ if eq .chezmoi.os "windows" -}}
 Write-Host ""
 Write-Host "Install mise packages."
 
+# mise config hash: {{ include "./private_dot_config/mise/config.toml.tmpl " | sha256sum }}
+
 Write-Host ""
 mise install --yes
-{{ else }}
-#!{{ lookPath "bash" }}
+{{ else -}}
+#!/usr/bin/env bash
+
+set -o errexit    # Exit on error. Append || true if you expect an error.
+set -o errtrace   # Exit on error inside any functions or subshells.
+set -o noclobber  # don't allow overwriting files
+set -o nounset    # Don't allow use of undefined vars. Use ${VAR:-} to use an undefined VAR.
+set -o pipefail   # Produce a failure return code if any pipeline command errors
+shopt -s failglob # Cause globs that don't get expanded to cause errors
 
 echo
 echo
 echo "Install mise packages."
+
+# mise config hash: {{ include "./private_dot_config/mise/config.toml.tmpl " | sha256sum }}
 
 echo
 mise install --yes
diff --git a/chezmoi/.chezmoiscripts/run_onchange_after_84-install-uv-packages.sh.tmpl b/chezmoi/.chezmoiscripts/run_onchange_after_84-install-uv-packages.sh.tmpl
--- a/chezmoi/.chezmoiscripts/run_onchange_after_84-install-uv-packages.sh.tmpl
+++ b/chezmoi/.chezmoiscripts/run_onchange_after_84-install-uv-packages.sh.tmpl
@@ -1,5 +1,4 @@
-# uv tools hash: {{ include "./private_dot_config/uv/tools.txt" | sha256sum }}
-{{  if eq .chezmoi.os "windows" }}
+{{ if eq .chezmoi.os "windows" -}}
 # Set strict error handling
 $ErrorActionPreference = "Stop"  # Exit on error
 Set-StrictMode -Version Latest   # Disallow undefined variables
@@ -28,6 +27,8 @@ fi
 # 1. Create a temp file
 $tmpfile = New-TemporaryFile
 
+# uv tools hash: {{ include "./private_dot_config/uv/tools.txt" | sha256sum }}
+
 # 2. Filter comments/blank lines and write to temp file
 Get-Content "./private_dot_config/uv/tools.txt" |
     Where-Object { $_ -notmatch '^\s*(#|$)' } |
@@ -37,10 +38,15 @@ Get-Content "./private_dot_config/uv/tools.txt" |
 Get-Content $tmpfile | ForEach-Object -Parallel {
     uv tool install --force -- $_
 }
-{{ else }}
+{{ else -}}
 #!/usr/bin/env bash
 
-set -euo pipefail
+set -o errexit    # Exit on error. Append || true if you expect an error.
+set -o errtrace   # Exit on error inside any functions or subshells.
+set -o noclobber  # don't allow overwriting files
+set -o nounset    # Don't allow use of undefined vars. Use ${VAR:-} to use an undefined VAR.
+set -o pipefail   # Produce a failure return code if any pipeline command errors
+shopt -s failglob # Cause globs that don't get expanded to cause errors
 
 echo
 echo
@@ -49,6 +55,8 @@ echo "Install uv tools."
 if ! pre-commit --version 2>&1 | grep -q pre-commit-uv ; then
     uv tool install pre-commit --with pre-commit-uv --force-reinstall
 fi
+
+# uv tools hash: {{ include "./private_dot_config/uv/tools.txt" | sha256sum }}
 
 # create a temp file list with cleaned tool names
 tmpfile="$(mktemp)"
